version: "3"

volumes:
    grafana-data:
        driver: local
    prometheus-data:
        driver: local

services:
    apache:
        restart: always
        build: ./apache
        volumes:
            - ../..:/var/www/html
            - ./apache/php.ini:/usr/local/etc/php/php.ini
        environment:
            DB_DATABASE: kintsugi
            DB_USERNAME: local
            DB_HOST: 192.168.0.37
            SPHINX_HOST: 192.168.0.37
            DB_PASSWORD: local
            DB_ROOT_PASSWORD: test
        networks:
            - network1
        ports:
            - "8181:80"

    k6:
        container_name: k6
        image: loadimpact/k6
        volumes:
            - ./k6-tests:/tests
        networks:
            - network1

    cadvisor:
        container_name: cadvisor
        image: google/cadvisor
        restart: unless-stopped
        ports:
        - "8282:8080"
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - network1
    
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        restart: unless-stopped
        ports:
        - "9090:9090"
        volumes:
        - ./prometheus:/etc/prometheus
        - prometheus-data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - network1
        
    grafana:
        container_name: grafana
        image: grafana/grafana
        restart: unless-stopped
        ports:
        - "3000:3000"
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
        # - ./grafana:/etc/grafana
        - grafana-data:/var/lib/grafana
        networks:
            - network1
        
    loki:
        container_name: loki
        image: grafana/loki
        # restart: unless-stopped
        volumes:
            - ./loki:/etc/loki
        command:
            - '-config.file=/etc/loki/local-config.yaml'
        ports:
            - "3100:3100"
        networks:
            - network1
        
    promtail:
        image: grafana/promtail:2.2.1
        volumes:
        - /var/log:/var/log
        - ./promtail:/etc/promtail 
        command: -config.file=/etc/promtail/promtail-config.yaml
        networks:
            - network1
    
networks:
    network1:
        external:
            name: pandakintsugi_backend
